<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<OutputPath>..\..\AssetRipper\Source\0Bins\Ruri.AssemblyDumper\$(Configuration)\</OutputPath>
		<IntermediateOutputPath>..\..\AssetRipper\Source\0Bins\obj\Ruri.AssemblyDumper\$(Configuration)\</IntermediateOutputPath>
		<RootNamespace>Ruri.AssemblyDumper</RootNamespace>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Tpk\Tpk.TypeTrees.Json\Tpk.TypeTrees.Json.csproj" />
		<ProjectReference Include="..\..\Tpk\Tpk\Tpk.csproj" />
	</ItemGroup>

</Project>
