using AssetRipper.Primitives;
using AssetRipper.Tpk.TypeTrees.Json;
using Ruri.RipperHook;
using Ruri.RipperHook.Core;
using Ruri.RipperHook.Core.TypeTree;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Ruri.Tpk.Pipeline;

/// <summary>
/// Diffs every dumped game type tree against the closest OFFICIAL Unity dump and reports exactly
/// where the fork deviates -- which is the same thing as reporting every place a hook is needed.
///
/// Why this exists: the runtime already interprets the game's own trees, so a fork's extra field is
/// read and then dropped on the floor, silently, because stock AssetRipper has nowhere to put it.
/// A fork's extra ENUM VALUE is worse: stock code that decides by negation (<c>!= A &amp;&amp; != B</c>)
/// swallows the unknown value into the wrong branch and crashes or exports garbage. EndField's
/// <c>m_BlendSequenceData</c> / <c>m_BlendType == 5</c> was exactly that, and it was found only after
/// it took down a whole export. This pass turns "find out when it bites" into a checklist.
///
/// Two things it does that hand inspection kept getting wrong:
///   * it reports the FIRST version a drift appears in, across the whole lineage, so a hook lands on
///     that version instead of being dumped into a Common class that over-applies;
///   * it snaps each game's fabricated engine version to the nearest real one
///     (see <see cref="OfficialTypeTreeIndex.ResolveClosest"/>) rather than trusting it.
///
/// Output is a report plus ready-to-fill capability stubs. The stubs are written OUTSIDE the compiled
/// tree on purpose: an empty generated hook that compiles is dead code pretending to be coverage, so
/// a stub only becomes real when someone moves it in and writes the backfill.
/// </summary>
internal static class TypeTreeDrift
{
    private const string CommonDirectoryName = "Common";
    private const string AckFileName = "drift-ack.json";

    /// <summary>Container shapes are structural, not fields anyone hooks; diffing them is pure noise.</summary>
    private static readonly HashSet<string> ContainerTypes = new(StringComparer.Ordinal)
    {
        "vector", "Array", "map", "pair", "set", "staticvector", "TypelessData",
    };

    public enum DriftKind
    {
        AddedField,
        RemovedField,
        RetypedField,
        ReorderedFields,
    }

    private sealed record Drift(DriftKind Kind, string OwnerType, string Field, string Detail)
    {
        public string Key => $"{Kind}|{OwnerType}|{Field}";

        /// <summary>
        /// Path to the owning struct from the class root, or null when it sits behind an array and
        /// therefore has no single addressable path. <c>[TypeTreePostRead]</c> captures are
        /// slash-joined FIELD chains, so only a non-null path can be turned into a real capture --
        /// emitting a bare field name for an array-nested node would produce a capture that silently
        /// never matches.
        /// </summary>
        public string? OwnerPath { get; init; }
    }

    /// <summary>A struct as it appears in one tree: its field list and how to reach it from the root.</summary>
    private sealed record StructShape(List<(string Name, string Type)> Fields, string? Path);

    /// <summary>One drift, plus where it first shows up and which classes carry it.</summary>
    private sealed record Aggregated(Drift Drift, string FirstVersion, SortedSet<string> Classes, SortedSet<string> Versions);

    private sealed record AckEntry(string Lineage, string Key, string Reason);

    public static void Run(string dumpRoot, string outputDirectory)
    {
        OfficialTypeTreeIndex official = new();
        Console.WriteLine($"[Drift] upstream publishes {official.Available.Count} official dumps");

        List<AckEntry> acknowledged = ReadAck(dumpRoot);
        HashSet<string> handledByHook = ScanHandledClasses();
        Directory.CreateDirectory(outputDirectory);

        StringBuilder report = new();
        report.AppendLine("# TypeTree drift vs official Unity");
        report.AppendLine();
        report.AppendLine("Generated by `Ruri.Tpk --drift`. Every row is a place the fork's serialized shape");
        report.AppendLine("differs from stock Unity, i.e. a place stock AssetRipper's assumptions may not hold.");
        report.AppendLine("`First` is the earliest game version carrying it -- put the hook's `[Since]` there.");
        report.AppendLine();

        int totalNew = 0;

        foreach (DirectoryInfo lineageDirectory in new DirectoryInfo(dumpRoot).GetDirectories())
        {
            if (lineageDirectory.Name is CommonDirectoryName or "output" || lineageDirectory.Name.StartsWith('.'))
            {
                continue;
            }

            List<(string Version, string Path)> versions = new();
            foreach (DirectoryInfo versionDirectory in lineageDirectory.GetDirectories())
            {
                string infoPath = Path.Combine(versionDirectory.FullName, "info.json");
                if (File.Exists(infoPath))
                {
                    versions.Add((versionDirectory.Name, infoPath));
                }
            }
            if (versions.Count == 0)
            {
                continue;
            }
            versions.Sort(static (left, right) => VersionKey.Compare(left.Version, right.Version));

            Dictionary<string, Aggregated> aggregated = new(StringComparer.Ordinal);
            UnityVersion? snappedTo = null;

            foreach ((string version, string path) in versions)
            {
                UnityInfo game = UnityInfo.ReadFromJsonFile(path);
                UnityVersion claimed = ReadClaimedVersion(path);
                UnityVersion resolved = official.ResolveClosest(claimed);
                snappedTo ??= resolved;
                Console.WriteLine($"[Drift] {lineageDirectory.Name}/{version}: claims {claimed} -> official {resolved}");

                UnityInfo stock = official.Fetch(resolved);
                Dictionary<string, List<StructShape>> stockTypes = FlattenAll(stock);

                foreach (UnityClass gameClass in game.Classes)
                {
                    UnityNode? root = gameClass.ReleaseRootNode ?? gameClass.EditorRootNode;
                    if (root is null)
                    {
                        continue;
                    }

                    Dictionary<string, List<StructShape>> gameTypes = new(StringComparer.Ordinal);
                    Flatten(root, string.Empty, gameTypes);

                    foreach ((string typeName, List<StructShape> gameShapes) in gameTypes)
                    {
                        if (!stockTypes.TryGetValue(typeName, out List<StructShape>? stockShapes))
                        {
                            continue; // A type stock Unity has no counterpart for -- nothing to diff against.
                        }

                        // A game shape that matches ANY stock instantiation of this name exactly is
                        // not drift -- it is the same template with the same payload.
                        foreach (StructShape gameShape in gameShapes.Where(g => !stockShapes.Exists(st => FieldsEqual(st.Fields, g.Fields))))
                        {
                        foreach (Drift drift in DiffFields(typeName, gameShape, ClosestShape(stockShapes, gameShape.Fields)))
                        {
                            string className = $"{gameClass.Name}({gameClass.TypeID})";
                            if (aggregated.TryGetValue(drift.Key, out Aggregated? existing))
                            {
                                existing.Classes.Add(className);
                                existing.Versions.Add(version);
                            }
                            else
                            {
                                aggregated.Add(drift.Key, new Aggregated(
                                    drift, version,
                                    new SortedSet<string>(StringComparer.Ordinal) { className },
                                    new SortedSet<string>(StringComparer.Ordinal) { version }));
                            }
                        }
                        }
                    }
                }
            }

            totalNew += WriteLineage(report, lineageDirectory.Name, snappedTo, aggregated, acknowledged, handledByHook, outputDirectory);
        }

        string reportPath = Path.Combine(outputDirectory, "typetree-drift.md");
        File.WriteAllText(reportPath, report.ToString());
        Console.WriteLine($"[Drift] {totalNew} unacknowledged drift point(s) -> {reportPath}");
    }

    // -----------------------------------------------------------------
    // diffing
    // -----------------------------------------------------------------

    /// <summary>
    /// Collapses a tree into "for each named struct, its ordered field list". Comparing by STRUCT
    /// rather than walking the two trees in lockstep is what makes an inserted field show up as one
    /// drift instead of desynchronising everything after it.
    /// </summary>
    /// <summary>
    /// Collects every DISTINCT shape a type name appears with. Unity's dumps monomorphize
    /// templates -- <c>Keyframe</c> shows up once per curve payload (<c>float</c>,
    /// <c>Quaternionf</c>, ...), <c>OffsetPtr</c> once per pointee -- so one name genuinely has
    /// several field lists at once. An earlier cut of this kept a single "richest" shape per name,
    /// and the cross-instantiation comparisons that fell out of it produced confidently wrong rows
    /// like "Keyframe.value is `float` in the fork but `Quaternionf` officially".
    /// </summary>
    private static void Flatten(UnityNode node, string? path, Dictionary<string, List<StructShape>> into)
    {
        if (node.SubNodes.Count > 0 && !ContainerTypes.Contains(node.TypeName))
        {
            List<(string Name, string Type)> fields = node.SubNodes.ConvertAll(sub => (sub.Name, sub.TypeName));
            if (!into.TryGetValue(node.TypeName, out List<StructShape>? shapes))
            {
                shapes = new List<StructShape>();
                into.Add(node.TypeName, shapes);
            }

            int index = shapes.FindIndex(shape => FieldsEqual(shape.Fields, fields));
            if (index < 0)
            {
                shapes.Add(new StructShape(fields, path));
            }
            else if (shapes[index].Path is null && path is not null)
            {
                // Same shape seen again, this time somewhere addressable -- keep the usable path.
                shapes[index] = shapes[index] with { Path = path };
            }
        }

        foreach (UnityNode sub in node.SubNodes)
        {
            // Descending through a container loses addressability: a capture path names one node,
            // and everything under an array exists once per element.
            // Sanitized, because the runtime builds capture paths from the SAME transform
            // (TypeTreeNameFixer) -- a raw `data` would never match the runtime's `m_Data`.
            string fixedName = TypeTreeNameFixer.GetValidFieldName(sub.Name);
            string? childPath = ContainerTypes.Contains(sub.TypeName) || path is null
                ? null
                : path.Length == 0 ? fixedName : $"{path}/{fixedName}";
            Flatten(sub, ContainerTypes.Contains(node.TypeName) ? null : childPath, into);
        }
    }

    private static Dictionary<string, List<StructShape>> FlattenAll(UnityInfo info)
    {
        Dictionary<string, List<StructShape>> types = new(StringComparer.Ordinal);
        foreach (UnityClass unityClass in info.Classes)
        {
            UnityNode? root = unityClass.ReleaseRootNode ?? unityClass.EditorRootNode;
            if (root is not null)
            {
                Flatten(root, string.Empty, types);
            }
        }
        return types;
    }

    private static bool FieldsEqual(List<(string Name, string Type)> left, List<(string Name, string Type)> right)
    {
        if (left.Count != right.Count)
        {
            return false;
        }
        for (int i = 0; i < left.Count; i++)
        {
            if (!string.Equals(left[i].Name, right[i].Name, StringComparison.Ordinal)
                || !string.Equals(left[i].Type, right[i].Type, StringComparison.Ordinal))
            {
                return false;
            }
        }
        return true;
    }

    /// <summary>
    /// The stock shape a drifted game shape is diffed against: the one sharing the most field
    /// names. With template monomorphs in the set, "closest" is what pairs the float Keyframe with
    /// the float Keyframe instead of whichever instantiation happened to be visited first.
    /// </summary>
    private static StructShape ClosestShape(List<StructShape> candidates, List<(string Name, string Type)> fields)
    {
        HashSet<string> names = new(fields.Select(static f => f.Name), StringComparer.Ordinal);
        StructShape best = candidates[0];
        int bestScore = -1;
        foreach (StructShape candidate in candidates)
        {
            int score = candidate.Fields.Count(f => names.Contains(f.Name));
            if (score > bestScore)
            {
                best = candidate;
                bestScore = score;
            }
        }
        return best;
    }

    private static IEnumerable<Drift> DiffFields(string typeName, StructShape gameShape, StructShape stockShape)
    {
        List<(string Name, string Type)> game = gameShape.Fields;
        List<(string Name, string Type)> stock = stockShape.Fields;
        string? ownerPath = gameShape.Path;

        Dictionary<string, string> stockByName = new(StringComparer.Ordinal);
        foreach ((string name, string type) in stock)
        {
            stockByName[name] = type;
        }
        Dictionary<string, string> gameByName = new(StringComparer.Ordinal);
        foreach ((string name, string type) in game)
        {
            gameByName[name] = type;
        }

        foreach ((string name, string type) in game)
        {
            if (!stockByName.TryGetValue(name, out string? stockType))
            {
                yield return new Drift(DriftKind.AddedField, typeName, name,
                    $"`{type} {name}` exists only in the fork -- stock AssetRipper has no field to bind it to, so it is read and discarded.")
                { OwnerPath = ownerPath };
            }
            else if (stockType != type)
            {
                yield return new Drift(DriftKind.RetypedField, typeName, name,
                    $"`{name}` is `{type}` in the fork but `{stockType}` officially.")
                { OwnerPath = ownerPath };
            }
        }

        foreach ((string name, string type) in stock)
        {
            if (!gameByName.ContainsKey(name))
            {
                yield return new Drift(DriftKind.RemovedField, typeName, name,
                    $"`{type} {name}` is missing from the fork -- whatever stock code reads it gets a default.")
                { OwnerPath = ownerPath };
            }
        }

        // Order is the binary layout. Same names in a different sequence means every reader that
        // assumes stock order is wrong, so it is called out separately from add/remove.
        List<string> sharedGame = game.FindAll(f => stockByName.ContainsKey(f.Name)).ConvertAll(f => f.Name);
        List<string> sharedStock = stock.FindAll(f => gameByName.ContainsKey(f.Name)).ConvertAll(f => f.Name);
        if (!sharedGame.SequenceEqual(sharedStock, StringComparer.Ordinal))
        {
            yield return new Drift(DriftKind.ReorderedFields, typeName, "*",
                $"shared fields are ordered `{string.Join(", ", sharedGame)}` in the fork but `{string.Join(", ", sharedStock)}` officially.")
            { OwnerPath = ownerPath };
        }
    }

    // -----------------------------------------------------------------
    // reporting + stub generation
    // -----------------------------------------------------------------

    private static int WriteLineage(
        StringBuilder report,
        string lineage,
        UnityVersion? snappedTo,
        Dictionary<string, Aggregated> aggregated,
        List<AckEntry> acknowledged,
        HashSet<string> handledByHook,
        string outputDirectory)
    {
        HashSet<string> ackKeys = new(
            acknowledged.Where(a => a.Lineage == lineage).Select(a => a.Key), StringComparer.Ordinal);

        List<Aggregated> rows = aggregated.Values.ToList();
        rows.Sort(static (left, right) =>
        {
            int cmp = VersionKey.Compare(left.FirstVersion, right.FirstVersion);
            if (cmp != 0)
            {
                return cmp;
            }
            cmp = string.CompareOrdinal(left.Drift.OwnerType, right.Drift.OwnerType);
            return cmp != 0 ? cmp : string.CompareOrdinal(left.Drift.Field, right.Drift.Field);
        });

        List<Aggregated> fresh = rows.FindAll(row => !ackKeys.Contains(row.Drift.Key));

        report.AppendLine($"## Lineage `{lineage}` (diffed against official {snappedTo})");
        report.AppendLine();
        report.AppendLine($"{rows.Count} drift point(s), {rows.Count - fresh.Count} acknowledged in `{AckFileName}`, **{fresh.Count} needing review**.");
        report.AppendLine();

        if (fresh.Count > 0)
        {
            report.AppendLine("| First | Kind | Struct | Field | Carried by | Note |");
            report.AppendLine("| --- | --- | --- | --- | --- | --- |");
            foreach (Aggregated row in fresh)
            {
                string carriers = string.Join(", ", row.Classes.Take(4)) + (row.Classes.Count > 4 ? $" +{row.Classes.Count - 4}" : string.Empty);
                string hooked = row.Classes.Any(c => handledByHook.Contains(StripId(c))) ? " _(class already has a TypeTree hook)_" : string.Empty;
                report.AppendLine($"| `{row.FirstVersion}` | {row.Drift.Kind} | `{row.Drift.OwnerType}` | `{row.Drift.Field}` | {carriers} | {row.Drift.Detail}{hooked} |");
            }
            report.AppendLine();

            WriteStubs(lineage, fresh, outputDirectory);
        }

        return fresh.Count;
    }

    /// <summary>
    /// Emits one capability skeleton per (first version, class) that carries unacknowledged ADDED
    /// fields -- the wiring (game, since-version, class id, capture paths) is exactly what the diff
    /// already knows, so it is filled in; the decode is left as a hole because only a human knows
    /// what an ACL buffer or a nested shader blob means.
    /// </summary>
    private static void WriteStubs(string lineage, List<Aggregated> fresh, string outputDirectory)
    {
        if (ResolveGame(lineage) is not GameType game)
        {
            Console.WriteLine($"[Drift] lineage {lineage} maps to no GameType (retired engine) -- report only, no stubs.");
            return;
        }
        string hookNamespace = ResolveNamespace(game);

        var groups = fresh
            .Where(row => row.Drift.Kind == DriftKind.AddedField)
            .SelectMany(row => row.Classes.Select(cls => (Class: cls, Row: row)))
            .GroupBy(pair => (pair.Row.FirstVersion, pair.Class));

        string stubDirectory = Path.Combine(outputDirectory, "stubs", lineage);
        foreach (var group in groups)
        {
            (string version, string className) = group.Key;
            string bareName = StripId(className);
            int classId = ParseId(className);
            string identifier = $"Drift_{Sanitize(version)}_{Sanitize(bareName)}";

            // Only nodes with a single addressable path become captures. The rest live behind an
            // array (one instance per element), so they are listed for a human instead of being
            // emitted as a path that would compile and then never match anything.
            List<string> capturePaths = group
                .Where(pair => pair.Row.Drift.OwnerPath is not null)
                .Select(pair => TypeTreeNameFixer.GetValidFieldName(pair.Row.Drift.Field) is string leaf
                    && pair.Row.Drift.OwnerPath!.Length == 0
                        ? leaf
                        : $"{pair.Row.Drift.OwnerPath}/{TypeTreeNameFixer.GetValidFieldName(pair.Row.Drift.Field)}")
                .Distinct(StringComparer.Ordinal)
                .Order(StringComparer.Ordinal)
                .ToList();
            List<string> unaddressable = group
                .Where(pair => pair.Row.Drift.OwnerPath is null)
                .Select(pair => $"{pair.Row.Drift.OwnerType}.{pair.Row.Drift.Field}")
                .Distinct(StringComparer.Ordinal)
                .Order(StringComparer.Ordinal)
                .ToList();
            string captures = string.Join(", ", capturePaths.Select(static p => $"\"{p}\""));

            StringBuilder code = new();
            code.AppendLine("// <auto-generated> by Ruri.Tpk --drift. NOT compiled where it is written.");
            code.AppendLine("// Move it into the game's hook tree and implement the backfill, or record the drift in");
            code.AppendLine($"// {AckFileName} if stock AssetRipper genuinely needs nothing for it.");
            code.AppendLine("using AssetRipper.SourceGenerated;");
            code.AppendLine("using Ruri.RipperHook.Core.Capabilities;");
            code.AppendLine("using Ruri.RipperHook.Core.TypeTree;");
            code.AppendLine();
            code.AppendLine($"namespace {hookNamespace};");
            code.AppendLine();
            code.AppendLine("/// <summary>");
            foreach (var pair in group)
            {
                code.AppendLine($"/// {pair.Row.Drift.OwnerType}.{pair.Row.Drift.Field}: {pair.Row.Drift.Detail}");
            }
            if (unaddressable.Count > 0)
            {
                code.AppendLine("///");
                code.AppendLine("/// Behind an array, so there is no single capture path -- reach these from the asset itself:");
                foreach (string entry in unaddressable)
                {
                    code.AppendLine($"///   {entry}");
                }
            }
            code.AppendLine("/// </summary>");
            code.AppendLine($"[GameCapabilities(GameType.{game})]");
            code.AppendLine($"public static class {identifier}");
            code.AppendLine("{");
            code.AppendLine($"    [Since(\"{version}\")]");
            code.AppendLine($"    [TypeTreePostRead((ClassIDType){classId} /* {bareName} */, Slot = \"{Sanitize(bareName)}Drift\"{(capturePaths.Count > 0 ? $", Captures = [{captures}]" : string.Empty)})]");
            code.AppendLine("    public static void PostRead(TypeTreeReadContext context)");
            code.AppendLine("    {");
            code.AppendLine("        throw new NotImplementedException(\"Backfill the captured fork-only nodes onto the stock asset.\");");
            code.AppendLine("    }");
            code.AppendLine("}");

            Directory.CreateDirectory(stubDirectory);
            File.WriteAllText(Path.Combine(stubDirectory, $"{identifier}.cs"), code.ToString());
        }
    }

    /// <summary>
    /// Classes already carrying a TypeTree-level hook, read straight out of the hook sources. This
    /// only annotates the report -- a drift is never suppressed by it, because a hook on a class says
    /// nothing about whether THIS field is the one it handles.
    /// </summary>
    private static HashSet<string> ScanHandledClasses()
    {
        HashSet<string> handled = new(StringComparer.Ordinal);
        string hookRoot = RepoLayout.HookSourceRoot;
        if (!Directory.Exists(hookRoot))
        {
            return handled;
        }

        Regex pattern = new(@"\[TypeTree(?:PostRead|ValueFix|NodeGate)\(\s*(?:ClassIDType\.(\w+)|\(ClassIDType\)(\d+))", RegexOptions.Compiled);
        foreach (string file in Directory.EnumerateFiles(hookRoot, "*.cs", SearchOption.AllDirectories))
        {
            foreach (Match match in pattern.Matches(File.ReadAllText(file)))
            {
                handled.Add(match.Groups[1].Success ? match.Groups[1].Value : match.Groups[2].Value);
            }
        }
        return handled;
    }

    private static List<AckEntry> ReadAck(string dumpRoot)
    {
        string path = Path.Combine(dumpRoot, AckFileName);
        if (!File.Exists(path))
        {
            return new List<AckEntry>();
        }

        List<AckEntry> entries = new();
        foreach (JsonElement element in JsonDocument.Parse(File.ReadAllText(path)).RootElement.EnumerateArray())
        {
            entries.Add(new AckEntry(
                element.GetProperty("Lineage").GetString() ?? string.Empty,
                element.GetProperty("Key").GetString() ?? string.Empty,
                element.TryGetProperty("Reason", out JsonElement reason) ? reason.GetString() ?? string.Empty : string.Empty));
        }
        return entries;
    }

    private static UnityVersion ReadClaimedVersion(string infoPath)
    {
        using StreamReader reader = new(infoPath);
        char[] window = new char[4096];
        int read = reader.Read(window, 0, window.Length);
        string head = new(window, 0, read);

        const string marker = "\"Version\"";
        int start = head.IndexOf(marker, StringComparison.Ordinal);
        if (start >= 0)
        {
            int open = head.IndexOf('"', head.IndexOf(':', start + marker.Length) + 1);
            int close = head.IndexOf('"', open + 1);
            if (open > 0 && close > open)
            {
                return UnityVersion.Parse(head[(open + 1)..close]);
            }
        }

        throw new InvalidDataException($"[Drift] {infoPath} has no readable \"Version\" property.");
    }

    private static string StripId(string className)
    {
        int paren = className.IndexOf('(');
        return paren < 0 ? className : className[..paren];
    }

    private static int ParseId(string className)
    {
        int open = className.IndexOf('(');
        int close = className.IndexOf(')');
        return open >= 0 && close > open && int.TryParse(className[(open + 1)..close], out int id) ? id : -1;
    }

    private static string Sanitize(string value)
    {
        StringBuilder builder = new(value.Length);
        foreach (char c in value)
        {
            builder.Append(char.IsLetterOrDigit(c) ? c : '_');
        }
        return builder.ToString();
    }

    /// <summary>
    /// A lineage directory is named after its <see cref="CustomEngineType"/> value (FRAMEWORK.md §10),
    /// so the game a dump belongs to is read from the linked enum rather than guessed from the digits.
    /// A number with no member is a retired engine whose dumps are still around -- it still gets a
    /// report, it just cannot get compilable stubs, so say so instead of emitting broken code.
    /// </summary>
    private static GameType? ResolveGame(string lineage)
    {
        if (!byte.TryParse(lineage, out byte value))
        {
            return null;
        }
        string? engineName = Enum.GetName((CustomEngineType)value);
        return engineName is not null && Enum.TryParse(engineName, out GameType game) ? game : null;
    }

    /// <summary>
    /// The namespace a game's hooks actually live in, read out of the tree itself -- EndField's is
    /// <c>Ruri.RipperHook.Endfield</c>, which no amount of casing convention would have produced from
    /// <c>GameType.EndField</c>.
    /// </summary>
    private static string ResolveNamespace(GameType game)
    {
        string fallback = $"Ruri.RipperHook.{game}";
        if (!Directory.Exists(RepoLayout.HookSourceRoot))
        {
            return fallback;
        }

        Regex declaration = new($@"\[GameCapabilities\(GameType\.{game}\)\]", RegexOptions.Compiled);
        Regex namespaceLine = new(@"^namespace\s+([\w.]+)\s*;", RegexOptions.Compiled | RegexOptions.Multiline);
        foreach (string file in Directory.EnumerateFiles(RepoLayout.HookSourceRoot, "*.cs", SearchOption.AllDirectories))
        {
            string text = File.ReadAllText(file);
            if (declaration.IsMatch(text) && namespaceLine.Match(text) is { Success: true } match)
            {
                return match.Groups[1].Value;
            }
        }
        return fallback;
    }
}
